import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster"
// import { getUser } from "@/lib/auth";

// export async function generateMetadata(): Promise<Metadata> {
//   // let user = null;
//   // try {
//   //   // user = await getUser();
//   //   console.log(user,'...........................')
//   // } catch (error) {
//   //   console.error("Error fetching user:", error);
//   // }

//   // return {
//   //   title: user ? `Welcome, ${user.name || user.email}` : "Create Next App",
//   //   description: "Generated by create next app",
//   // };
// }

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // let user = null;
  // try {
  //   user = await getUser();
  // } catch (error) {
  //   console.error("Error fetching user:", error);
  // }

  return (
    <html lang="en">
      <body>
        {/* {user && <div>Logged in as: {user.email}</div>} */}
        {children}
        <Toaster />
      </body>
    </html>
  );
}